version: '3'
services:
  xonotic-server:
    build: .
    image: tguruslan/xonotic-server
    container_name: xonotic-server
    volumes:
      - ./Xonotic:/srv/Xonotic
      - ./data:/root/.xonotic/data
    ports:
     - 26000:26000/udp
    restart: always
